### PR TITLE
Rename: elements -> core-elements

### PR DESCRIPTION
**Pull request by manolo**
Connected to vaadin/components-team-tasks#50
Closes: #27

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-elements/28)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[bower.json, line 2 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-elements/28#-K5ZptPiM95CLxGeTiST:-K5ZptPiM95CLxGeTiSU:166336553) ([raw file](https://github.com/vaadin/vaadin-elements/blob/c17d81e40920bc3ef19e53900ee7370dff3fb4d1/bower.json#L2)):*
This isn't identical to #27. At least the name here is different. Something else?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-elements/28)*

**Comment by Saulis** [comment]
Review status: 0 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[bower.json, line 7 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-elements/28#-K5Zpe7V83CdYekQZmYE:-K5Zpe7V83CdYekQZmYF:1152917742) ([raw file](https://github.com/vaadin/vaadin-elements/blob/c17d81e40920bc3ef19e53900ee7370dff3fb4d1/bower.json#L7)):*
@jounik should the description and keywords emphasize on 'free' and/or 'open source' ? 

---

*[bower.json, line 10 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-elements/28#-K5ZpsFVssgJ1jmwUcZo:-K5ZpsFVssgJ1jmwUcZp:1931506126) ([raw file](https://github.com/vaadin/vaadin-elements/blob/c17d81e40920bc3ef19e53900ee7370dff3fb4d1/bower.json#L10)):*
Should we have 'vaadin' 'elements' also as keywords?

---

*[README.md, line 70 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-elements/28#-K5ZqBb7IPCkp3u9HDXP:-K5ZqBb7IPCkp3u9HDXQ:-2123363812) ([raw file](https://github.com/vaadin/vaadin-elements/blob/c17d81e40920bc3ef19e53900ee7370dff3fb4d1/README.md#L70)):*
Not sure if the anchor is going to be changed to `#core-elements` ? @tehapo @jounik ?

---

*[tasks/docsite.js, line 50 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-elements/28#-K5ZqznNnh3qLqTzipYW:-K5ZqznNnh3qLqTzipYX:1359839747) ([raw file](https://github.com/vaadin/vaadin-elements/blob/c17d81e40920bc3ef19e53900ee7370dff3fb4d1/tasks/docsite.js#L50)):*
Use `config.coreElements` instead and rename the property from `elements` to `coreElements` in `config.js`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-elements/28)*

**Comment by jounik** [comment]
Review status: 0 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[bower.json, line 7 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-elements/28#-K5Zpe7V83CdYekQZmYE:-K5ZrsgJVS9IKYl4C_JD:677251276) ([raw file](https://github.com/vaadin/vaadin-elements/blob/c17d81e40920bc3ef19e53900ee7370dff3fb4d1/bower.json#L7)):*
Yes.

---

*[bower.json, line 10 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-elements/28#-K5ZpsFVssgJ1jmwUcZo:-K5ZrwXzlgUX1EGq6_aF:160394146) ([raw file](https://github.com/vaadin/vaadin-elements/blob/c17d81e40920bc3ef19e53900ee7370dff3fb4d1/bower.json#L10)):*
Yes

---

*[README.md, line 70 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-elements/28#-K5ZqBb7IPCkp3u9HDXP:-K5Zs5gtqRjMB_mM8Vc4:-414662921) ([raw file](https://github.com/vaadin/vaadin-elements/blob/c17d81e40920bc3ef19e53900ee7370dff3fb4d1/README.md#L70)):*
No, I don’t think that’s needed at least now. Chart elements might go under the same hash eventually as well.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-elements/28)*

**Comment by manolo** [comment]
Review status: 0 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[tasks/docsite.js, line 50 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-elements/28#-K5ZqznNnh3qLqTzipYW:-K5ZwPJgE1YhKBHst2jC:424474447) ([raw file](https://github.com/vaadin/vaadin-elements/blob/c17d81e40920bc3ef19e53900ee7370dff3fb4d1/tasks/docsite.js#L50)):*
good catch, actually it was core_elements in the other PR, but something happened with cherry-pick/merge

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-elements/28)*

**Comment by manolo** [comment]
Review status: 0 of 11 files reviewed at latest revision, 5 unresolved discussions.

---

*[bower.json, line 2 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-elements/28#-K5ZptPiM95CLxGeTiST:-K5_F78RyncXVI5uMPRR:-499146009) ([raw file](https://github.com/vaadin/vaadin-elements/blob/c17d81e40920bc3ef19e53900ee7370dff3fb4d1/bower.json#L2)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-elements/28)*

**Comment by Saulis** [comment]
Reviewed 8 of 11 files at r1, 3 of 4 files at r2.
Review status: 10 of 11 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-elements/28)*

**Comment by tomivirkki** [comment]
lgtm

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-elements/28#-:-K5_U_3ogUQxEBDU3W5b:677819321)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 2 files at r3.
Review status: 10 of 11 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-elements/28)*

**Pull request merged**
